apiVersion: v1
kind: Secret
metadata:
  name: dockerconfigjson
  namespace: cinemaabyss
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJnaGNyLmlvIjogewoJCQkiYXV0aCI6ICJkbXhoWkdsemJHRjJaV2R2T21kb2NGODJTVXA0Wm1oRlREWjBVVlUzT0doeVNVaHdZV2htY0dOQ01FaE1VRk13TVRkaWVtYz0iCgkJfSwKCQkicmVnaXN0cnkueWFuZGV4Lm5ldCI6IHsKCQkJImF1dGgiOiAiZG14aFpHbHpiR0YyWldkdk9rRlJRVVF0Y1VwVFN6VjFaRUZCUVVWRFJVSlJXVVZTYm5Jd1ptdHNUR1EyZDBOcVF6VndTUT09IgoJCX0KCX0sCgkiY3VycmVudENvbnRleHQiOiAiY29saW1hIgp9
type: kubernetes.io/dockerconfigjson
