apiVersion: apps/v1
kind: Deployment
metadata:
  name: proxy-service
  namespace: cinemaabyss
spec:
  replicas: 1
  selector:
    matchLabels:
      app: proxy-service
  template:
    metadata:
      labels:
        app: proxy-service
    spec:
      containers:
        - name: proxy-service
          image: ghcr.io/vladislavego/architecture-cinemaabyss/proxy-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          env:
            - name: PORT
              value: "8000"
            - name: MONOLITH_URL
              valueFrom:
                configMapKeyRef:
                  name: cinemaabyss-config
                  key: MONOLITH_URL
            - name: MOVIES_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: cinemaabyss-config
                  key: MOVIES_SERVICE_URL
            - name: EVENTS_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: cinemaabyss-config
                  key: EVENTS_SERVICE_URL
            - name: GRADUAL_MIGRATION
              valueFrom:
                configMapKeyRef:
                  name: cinemaabyss-config
                  key: GRADUAL_MIGRATION
            - name: MOVIES_MIGRATION_PERCENT
              valueFrom:
                configMapKeyRef:
                  name: cinemaabyss-config
                  key: MOVIES_MIGRATION_PERCENT
      imagePullSecrets:
        - name: dockerconfigjson
---
apiVersion: v1
kind: Service
metadata:
  name: proxy-service
  namespace: cinemaabyss
spec:
  selector:
    app: proxy-service
  ports:
    - name: http
      port: 8000
      targetPort: 8000
      protocol: TCP
  type: ClusterIP